### ISSUE TITLE
指纹识别方式

### ISSUE THREAD

**Issue by Ashomes** [chainreactors/fingers#3]
如果证书带有WEB指纹信息呢，有计划做识别吗

**Comment by M09Ic** [comment]
在原生指纹库中目前有个比较简易的, 只会证书的domain. 

如果有更多场景, 欢迎提供案例. 

```
- name: 腾讯云CDN
  rule:
    - regexps:
        header:
          - X-NWS-LOG-UUID
        cert:
          - cdn.myqcloud.com
```
